[package]
name = "fou-lstm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
candle-core = "0.3.3"
candle-nn = "0.3.3"
stochastic-rs = "0.3.5"
